# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Jungyun Kim
title: a Ph.D. candidate
email: jungyun@yonsei.ac.kr
# email_title: Email (Email title override)
#phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
website: https://jungyunkim.tistory.com/
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: jekyllrb
github_username:  jungyun24
#stackoverflow_username: "00000001"
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
instagram_username: _yunny__
#linkedin_username: jekyll
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
orcid_username: 0009-0008-6782-342X
googlescholar_username: f7IH2MUAAAAJ

# Additional icon links
#additional_links:
#- title: Link name
#  icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: /images/profile.jpg (eg. images/profile.jpg)
about_content: |
  Research Interests  
    - Cross Model Compatibility  
    - Multi-modal  
    - Cross-modal

content:
  # - title: Projects # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: left
  #       border: weak  # Value of `weak` will display a weak border below this item. # Any 
  #                     # other value (or no value) means no border will be displayed
  #       title: Project name
  #       link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
  #       link_text: Link Text
  #       additional_links:
  #         - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #           icon: fab fa-github
  #           url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
  #         - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #           icon: fab fa-github
  #           url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
  #       quote: >
  #         Short overview of the project (optional)
  #       description: | # this will include new lines to allow paragraphs
  #         Description about the work on/with the project
  - title: Experience
    layout: list
    content:
      - layout: top
        title: Division of ICT, Semiconductor & Electronic Engineering, Yeungnam University College
        sub_title: Adjunct Lecturer
        caption: 2025
        link: https://eie.ync.ac.kr/eie/Main.do
      - layout: top
        title: UNIST
        sub_title: Researcher
        caption: 2022
        link: https://unist-kor.unist.ac.kr/
      - layout: top
        title: Autonics
        sub_title: Intern
        caption: 2020
        link: https://www.autonics.com/kr/main

  - title: Education
    layout: list
    content:
      - layout: left
        title: Yonsei University
        sub_title: PhD in Electronic and Electronic Engineering
        caption: 2025 - Present
        # quote: >
        #   Major in Biometric and Deep Learning.
        description: |
          • Specialized in cross-modal and multi-modal tasks.  

      - layout: left
        title: Yonsei University
        sub_title: MS in Electronic and Electronic Engineering
        caption: 2023 - 2025
        # quote: >
        #   Major in Biometric and Deep Learning.
        description: |
          • Specialized in cross-model compatibility tasks.  
          • GPA: 3.96/4.3

      - layout: left
        title: Dong-A University
        sub_title: BS in Electronic Engineering
        caption: 2016 - 2021
        # quote: >
        #   Major in Electrical Systems.
        description: |
          • Specialized in signal processing and embedded systems.  
          • GPA: 4.38/4.5
          
  - title: Instructor of Record
    layout: list
    content:  
      - layout: top
        title: IOT programming practice (09512)
        sub_title: Division of ICT, Semiconductor & Electronic Engineering, Yeungnam University College
        caption: Fall 2025
      - layout: top
        title: Mobile Communication (04152)
        sub_title: Division of ICT, Semiconductor & Electronic Engineering, Yeungnam University College
        caption: Fall 2025
      - layout: top
        title: INTRODUCTORY DIGITAL LABS (EEE3313.06-00)
        sub_title: Department of Electrical and Electronic Engineering, Yonsei University
        caption: Spring 2025
      - layout: top
        title: Python Programming (07123)
        sub_title: Division of ICT, Semiconductor & Electronic Engineering, Yeungnam University College
        caption: Spring 2025
      - layout: top
        title: Digital Communication (04142)
        sub_title: Division of ICT, Semiconductor & Electronic Engineering, Yeungnam University College
        caption: Spring 2025

  - title: TA
    layout: list
    content:
      - layout: top
        title: SPCIAL TOPICS IN DEEP LEARNIING (EEE7331.01-00)
        sub_title: Department of Electrical and Electronic Engineering, Yonsei University
        caption: Fall 2025
      - layout: top
        title: INTRODUCTORY DIGITAL LABS (EEE3313.06-00)
        sub_title: Department of Electrical and Electronic Engineering, Yonsei University
        caption: Spring 2025
      - layout: top
        title: SPCIAL TOPICS IN DEEP LEARNIING (EEE7331.01-00)
        sub_title: Department of Electrical and Electronic Engineering, Yonsei University
        caption: Fall 2024
      - layout: top
        title: NEURAL NETWORK (EEE7501.01-00)
        sub_title: Department of Electrical and Electronic Engineering, Yonsei University
        caption: Spring 2024
      - layout: top
        title: SIGNAL AND SYSTEMS (EEE2060.05-00)
        sub_title: Department of Electrical and Electronic Engineering, Yonsei University
        caption: Fall 2023
      - layout: top
        title: PROBABILITY AND RANDOM VARIABLES (EEE3410.03-00)
        sub_title: Department of Electrical and Electronic Engineering, Yonsei University
        caption: Spring 2023






  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      This is where you can write a little more about yourself. You could title this section **Interests** and include some of your other interests.

      Or you could title it **Skills** and write a bit more about things that make you more desirable, like *leadership* or *teamwork*

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
